language: ruby
rvm:
  - 2.0.0
  - 2.2.0
  - ruby-head
env:
  - "RAILS_VERSION=4.0.0"
  - "RAILS_VERSION=4.2.0"
  - "RAILS_VERSION=master"
matrix:
  allow_failures:
    - rvm: ruby-head
    - env: "RAILS_VERSION=master"
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
install:
  - bundle install
notifications:
  email: false
branches:
  only:
    - master
