language: ruby
rvm:
  - 2.0.0
  - 2.2.0
  - ruby-head
env:
  - "RAILS_VERSION=4.0.0"
  - "RAILS_VERSION=4.2.0"
  - "RAILS_VERSION=master"
matrix:
  allow_failures:
    - rvm: ruby-head
    - env: "RAILS_VERSION=master"
install:
  - bundle install
notifications:
  email: false
